# Generated by Django 5.2.15 on 2026-09-25 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_rename_data_compra_data_criacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='tipo_pagamento',
            field=models.IntegerField(choices=[(1, 'Cartão de Crédito'), (2, 'Cartão de Débito'), (3, 'PIX'), (4, 'Boleto'), (5, 'Transferência Bancária'), (6, 'Dinheiro'), (7, 'Cheque'), (8, 'Outro')], default=1),
        ),
    ]
